- name: Deploy Windows Servers
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - node-config/nodes-wsus-server-kubevirt.yml

  roles:
  - ansible-role-kubevirt